// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HideButtonsController from "./hide_buttons_controller"
application.register("hide-buttons", HideButtonsController)

import InvoiceController from "./invoice_controller"
application.register("invoice", InvoiceController)

import PrintController from "./print_controller"
application.register("print", PrintController)
